name: .NET

on:
  push:
    branches: [ main ]

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
    - name: Run
      run: dotnet run
      env:
        MYAPP_SECRET: ${{ secrets.MYAPP_SECRET }}
        
